### ISSUE TITLE
Not compatible with the latest Crossplane

### ISSUE THREAD

**Issue by muvaf** [upbound/platform-ref-aws#27]
I'm getting the following error:
```console
$ kubectl crossplane install configuration registry.upbound.io/upbound/platform-ref-aws:v0.0.4
configuration.pkg.crossplane.io/platform-ref-aws created
$ k describe configurationrevision platform-ref-aws-7b134ebdd0d3
Events:
  Type     Reason       Age                From                                              Message
  ----     ------       ----               ----                                              -------
  Warning  LintPackage  62s (x3 over 62s)  packages/configurationrevision.pkg.crossplane.io  package is not compatible with Crossplane version (v0.0.1-38.g61109ab8)
```

cc @hasheddan could this be related to recent changes in `crossplane.yaml`?

**Comment by hasheddan** [comment]
@muvaf how did you install Crossplane? Looks like the version in your build is incorrect

**Comment by muvaf** [comment]
It was through the local `make build && cluster/local/kind.sh helm-install`

**Comment by hasheddan** [comment]
I am surprised you got `v0.0.1-38.g61109ab8` in that process (would expect a dirty build with `v0.14.0-rc` prefix), do you have a shallow clone of the repo? Using a dirty `v0.14.0-rc` version should work here because the constraints do allow for pre-release versions. However, when this is "production-ready" I would guess we would want the version constraints to not include pre-releases (i.e. `>=v0.14.0` rather than `>=v0.14.0-0`). When that is the case, you can still test the configuration with non-stable version by setting `spec.ignoreCrossplaneConstraints: true` https://doc.crds.dev/github.com/crossplane/crossplane/pkg.crossplane.io/Configuration/v1alpha1#spec-ignoreCrossplaneConstraints

**Comment by muvaf** [comment]
I see. It probably has something to do with my local then. For dev, using `spec.ignoreCrossplaneConstraints: true` makes sense. Thanks!
