### ISSUE TITLE
Update with best practices and latest upstream functionality

### ISSUE THREAD

**Issue by jbw976** [upbound/platform-ref-aws#45]
There's been some great work in upstream Crossplane around compositions that we should incorporate into this reference platform.  The goal is to be a model source of best practices for writing Configurations.  For example:

* patchSets (named patches)
* Required patches
* bi-directional patching
* others from 1.0 and 1.1 releases

Here's an example from a recent PR comment: https://github.com/upbound/platform-ref-aws/pull/44#discussion_r591697797

**Comment by jbw976** [comment]
It would be good to do this for other reference platfoms too

**Comment by negz** [comment]
@sumbry is interested in taking this as his starter project.

**Comment by Piotr1215** [comment]
I've started working on this, tracking small task lists in our internal repo. All changes are going to go into [my fork](https://github.com/Piotr1215/platform-ref-aws).

:crossed_fingers: for many small PRs to come as opposed to one huge.

**Comment by jbw976** [comment]
Awesome @Piotr1215! Please feel free to use me as a reference our to bounce ideas off of 🙇‍♂️

**Comment by Piotr1215** [comment]
> Awesome @Piotr1215! Please feel free to use me as a reference our to bounce ideas off of bowing_man

I'm surely going to take you up on this offer :man_student:

**Comment by Piotr1215** [comment]
@hasheddan :wave: I want to clean up the [crossplane.yaml](https://github.com/Piotr1215/platform-ref-aws/blob/acbc5dc6e0b6ccea0f8af92de3156e47ef8297dc/crossplane.yaml#L50) as suggested by @negz in a TODO in the file.

I wanted to confirm that we are not using the annotations starting with friendly*. I will include the annotations from Xpkg one-pager.

2 one-pagers referng to annotations for reference
- [Defunct](https://github.com/crossplane/crossplane/blob/3dac5904be7626d7ea60a52e3dbee4d52d5a9f3c/design/defunct/one-pager-package-annotations.md)
- [Xpkg](https://github.com/crossplane/crossplane/blob/20d9ba0d22b6aab641d9b8047a4551dcd3a92607/docs/reference/xpkg.md)

**Comment by Piotr1215** [comment]
For reference, here are major themes from [v1.1.0](https://github.com/crossplane/crossplane/tree/v1.1.0) onwards. This list helps define what changes to make in the platform-ref-aws package.

Please feel free to add/correct if anything is missing.

## 1.1.x

### Bidirectional patching

Ref: https://github.com/crossplane/crossplane/pull/2077
This allows for specifying patches from composed resources back to the corresponding XR / XRC.

### Patch Sets

Ref: [Docs on GitHub ](https://github.com/crossplane/crossplane/blob/d2cbf6e55a87603aba364769e7d37a2b8d329bfb/docs/reference/composition.md?plain=1#L369
)

Allows for grouping patches as a named set.

### Required patches

Ref: https://github.com/crossplane/crossplane/pull/2133

Added support for Required fromFieldPath patches, which will cause rendering of composing resources to fail if a patch that is marked as Required is missing its fromFieldPath

### Naming composition templates

Ref: https://github.com/crossplane/crossplane/pull/2131

This enables reordering, as well as addition and deletion of templates in a Composition

### Adds parameters for Crossplane installation

Ref: https://github.com/crossplane/crossplane/pull/2105

Adds parameters to the Crossplane Helm chart for setting nodeSelector, tolerations, and affinity on the Crossplane and RBAC Manager Deployments

Idea :bulb: - this can be useful when installing Crossplane via helm chart on a more complex cluster.

## 1.2.x

No new notable features

## 1.3.x

### Multi -field patching

Ref: https://github.com/crossplane/crossplane/pull/2352

adds new CombineFromComposite and CombineToComposite patch types that can be used to patch from multiple Composite Resource (XR) fields to a single composed resource field, and vice versa.

### Kubectl crossplane can wait for operations to complete

Ref: https://github.com/crossplane/crossplane/pull/2345

## 1.4.x

### Composition Revisions

Ref: https://github.com/crossplane/crossplane/pull/2451
Ref2: https://github.com/crossplane/crossplane/pull/2500


Idea :bulb: Demo could show how to move to a new revision

### Patch merge options

Ref: https://github.com/crossplane/crossplane/pull/2409

Supports merging instead of replacing values in patches.

Idea :bulb: this is really cool!

## 1.5.x

### ToUpper/ToLower string transforms

Ref: https://github.com/crossplane/crossplane/pull/2463

## 1.6.x

No new notable features

**Comment by ytsarev** [comment]
@Piotr1215 incredibly useful summary!

**Comment by Piotr1215** [comment]
Closed by accident, reopening.

**Comment by jbw976** [comment]
I think @Piotr1215 did a great job of adding some extra Composition functionality and we're probably in a good place now
